# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.10
repos:
-   repo: local
    hooks:
    - id: isort
      additional_dependencies:
        - isort
      name: isort
      entry: isort
      language: python
      types: [ python ]
      args: [--settings-path=setup.cfg]
    - id: black
      additional_dependencies:
        - black
      name: black
      entry: black
      language: python
      types: [python]
      args: ["--skip-string-normalization"]
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      types: [ python ]
      additional_dependencies: [wemake-python-styleguide]
      args: [ --config=setup.cfg]
    - id: mypy
      additional_dependencies:
        - django
        - python-dotenv
        - beautifulsoup4
        - django-revproxy
        - celery
        - redis
        - mypy==1.8
        - django-stubs
        - psycopg2-binary
        - asyncpg
      name: mypy
      entry: mypy
      language: python
      types: [ python ]
      args: [ --config-file=setup.cfg ]
