version: '3.7'

services:
  postgres:
    image: 'postgres:latest'
    container_name: "postgres"
    env_file:
      - .env  # must define POSTGRES_USER, POSTGRES_PASSWORD and POSTGRES_DB
    volumes:
      - database_data:/var/lib/postgresql/data/  # persist data
    ports:
      - '8778:5432'  # required to access DB from host system
  web:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
      - gunicorn_socket:/gunicorn_socket
    ports:
      - '8000:8000'
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - postgres
  redis:
    image: redis:5
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

volumes:
  database_data:
  gunicorn_socket:
  redis_data:
