version: '3.7'

services:
  postgres_vpn:
    image: 'postgres:16-alpine3.19'
    container_name: "postgres_vpn"
    env_file:
      - .env  # must define POSTGRES_USER, POSTGRES_PASSWORD and POSTGRES_DB
    volumes:
      - database_data:/var/lib/postgresql/data/  # persist data
    ports:
      - '8778:5432'  # required to access DB from host system
  redis_vpn:
    image: redis:5
    container_name: 'redis_vpn'
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
  web_vpn:
    build:
      context: .
    container_name: 'web_vpn'
    volumes:
      - ./:/usr/src/app
      - gunicorn_socket:/gunicorn_socket
    env_file:
      - .env
    depends_on:
      - postgres_vpn
      - redis_vpn
  nginx_vpn:
    build:
      context: ./nginx/
    container_name: 'nginx_vpn'
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # nginx needs to access admin_static_files files
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./admin_static_files:/usr/src/app/admin_static_files
      - gunicorn_socket:/gunicorn_socket
    depends_on:
      - web_vpn

volumes:
  database_data:
  redis_data:
  gunicorn_socket:
