version: '3.7'

services:
  web:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
      - gunicorn_socket:/gunicorn_socket
    ports:
      - '8000:8000'
    expose:
      - 8000
    env_file:
      - .env
  redis:
    image: redis:5
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

volumes:
  gunicorn_socket:
  redis_data:
